### ISSUE TITLE
无法连接数据库，运行出错

### ISSUE THREAD

**Issue by Asphelzhn** [DragonistYJ/EduWatching#5]
运行无法连接上数据库，能否提供一下本地数据库sql，运行出错，能帮忙看一下问题吗，谢谢
(paddle) EduWatching-master$ python Main.py 
can't connect to db
W1014 19:54:15.955312 29675 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.0
W1014 19:54:15.958451 29675 device_context.cc:243] device: 0, cuDNN Version: 7.5.
Could not find QtWebEngineProcess
[29675:29675:1014/195418.707230:FATAL:zygote_host_impl_linux.cc(182)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid). 
#0 0x7f3759f020a5 <unknown>
#1 0x7f3759f17eca <unknown>
#2 0x7f375955afc3 <unknown>
#3 0x7f3759559c3b <unknown>
#4 0x7f375955a219 <unknown>
#5 0x7f375919d93a <unknown>
#6 0x7f37591a2e76 <unknown>
#7 0x7f3758cc0600 <unknown>
#8 0x7f3758cc1b25 <unknown>
#9 0x7f3758cb0ee9 <unknown>
#10 0x7f3758cb10be QtWebEngineCore::WebContentsAdapter::WebContentsAdapter()
#11 0x7f37caae7441 <unknown>
#12 0x7f37caae7f24 QWebEnginePage::QWebEnginePage()
#13 0x7f37caaf5ebb QWebEngineView::page()
#14 0x7f37e39763f9 meth_QWebEngineView_page
#15 0x5561866a016f _PyMethodDef_RawFastCallKeywords
#16 0x5561866d64b0 call_function
#17 0x55618671def2 _PyEval_EvalFrameDefault
#18 0x5561866703bd _PyEval_EvalCodeWithName
#19 0x556186671502 _PyObject_FastCallDict
#20 0x5561866dd16f slot_tp_init
#21 0x5561866d5eec _PyObject_FastCallKeywords
#22 0x55618671dea5 _PyEval_EvalFrameDefault
#23 0x55618666fdb2 _PyEval_EvalCodeWithName
#24 0x5561866711e3 PyEval_EvalCode
#25 0x55618677e1d2 run_mod
#26 0x55618678831e PyRun_FileExFlags
#27 0x55618678850b PyRun_SimpleFileExFlags
#28 0x5561867895f1 pymain_main
#29 0x55618678967c _Py_UnixMain
#30 0x7f380cf74830 __libc_start_main
#31 0x55618672e101 <unknown>

Received signal 6
#0 0x7f3759f020a5 <unknown>
#1 0x7f3758c43141 <unknown>
#2 0x7f3759f0243d <unknown>
#3 0x7f380d32f390 <unknown>
#4 0x7f380cf89428 gsignal
#5 0x7f380cf8b02a abort
#6 0x7f3759f01dc5 <unknown>
#7 0x7f3759f181ed <unknown>
#8 0x7f375955afc3 <unknown>
#9 0x7f3759559c3b <unknown>
#10 0x7f375955a219 <unknown>
#11 0x7f375919d93a <unknown>
#12 0x7f37591a2e76 <unknown>
#13 0x7f3758cc0600 <unknown>
#14 0x7f3758cc1b25 <unknown>
#15 0x7f3758cb0ee9 <unknown>
#16 0x7f3758cb10be QtWebEngineCore::WebContentsAdapter::WebContentsAdapter()
#17 0x7f37caae7441 <unknown>
#18 0x7f37caae7f24 QWebEnginePage::QWebEnginePage()
#19 0x7f37caaf5ebb QWebEngineView::page()
#20 0x7f37e39763f9 meth_QWebEngineView_page
#21 0x5561866a016f _PyMethodDef_RawFastCallKeywords
#22 0x5561866d64b0 call_function
#23 0x55618671def2 _PyEval_EvalFrameDefault
#24 0x5561866703bd _PyEval_EvalCodeWithName
#25 0x556186671502 _PyObject_FastCallDict
#26 0x5561866dd16f slot_tp_init
#27 0x5561866d5eec _PyObject_FastCallKeywords
#28 0x55618671dea5 _PyEval_EvalFrameDefault
#29 0x55618666fdb2 _PyEval_EvalCodeWithName
#30 0x5561866711e3 PyEval_EvalCode
#31 0x55618677e1d2 run_mod
#32 0x55618678831e PyRun_FileExFlags
#33 0x55618678850b PyRun_SimpleFileExFlags
#34 0x5561867895f1 pymain_main
#35 0x55618678967c _Py_UnixMain
#36 0x7f380cf74830 __libc_start_main
#37 0x55618672e101 <unknown>
  r8: 00007f380d31a770  r9: 00007f380d743700 r10: 0000000000000008 r11: 0000000000000206
 r12: 00007ffcb48ce7e0 r13: 00000000000000ac r14: 00007ffcb48cea10 r15: 00007ffcb48cf180
  di: 00000000000073eb  si: 00000000000073eb  bp: 00007f38094c7aa0  bx: 00007ffcb48cef60
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007f380cf89428  sp: 00007ffcb48ce678
  ip: 00007f380cf89428 efl: 0000000000000206 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by DragonistYJ** [comment]
数据库不是核心功能，你直接把数据库相关代码注释了，或者随便建一个能连上的数据库就行



---原始邮件---
发件人: "HarlingZhao"<notifications@github.com&gt;
发送时间: 2020年10月14日(周三) 晚上8:00
收件人: "DragonistYJ/EduWatching"<EduWatching@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [DragonistYJ/EduWatching] 无法连接数据库，运行出错 (#5)




 
运行无法连接上数据库，能否提供一下本地数据库sql，运行出错，能帮忙看一下问题吗，谢谢
 (paddle) EduWatching-master$ python Main.py
 can't connect to db
 W1014 19:54:15.955312 29675 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.0
 W1014 19:54:15.958451 29675 device_context.cc:243] device: 0, cuDNN Version: 7.5.
 Could not find QtWebEngineProcess
 [29675:29675:1014/195418.707230:FATAL:zygote_host_impl_linux.cc(182)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &amp;boot_pid).
 #0 0x7f3759f020a5 
 #1 0x7f3759f17eca 
 #2 0x7f375955afc3 
 #3 0x7f3759559c3b 
 #4 0x7f375955a219 
 #5 0x7f375919d93a 
 #6 0x7f37591a2e76 
 #7 0x7f3758cc0600 
 #8 0x7f3758cc1b25 
 #9 0x7f3758cb0ee9 
 #10 0x7f3758cb10be QtWebEngineCore::WebContentsAdapter::WebContentsAdapter()
 #11 0x7f37caae7441 
 #12 0x7f37caae7f24 QWebEnginePage::QWebEnginePage()
 #13 0x7f37caaf5ebb QWebEngineView::page()
 #14 0x7f37e39763f9 meth_QWebEngineView_page
 #15 0x5561866a016f _PyMethodDef_RawFastCallKeywords
 #16 0x5561866d64b0 call_function
 #17 0x55618671def2 _PyEval_EvalFrameDefault
 #18 0x5561866703bd _PyEval_EvalCodeWithName
 #19 0x556186671502 _PyObject_FastCallDict
 #20 0x5561866dd16f slot_tp_init
 #21 0x5561866d5eec _PyObject_FastCallKeywords
 #22 0x55618671dea5 _PyEval_EvalFrameDefault
 #23 0x55618666fdb2 _PyEval_EvalCodeWithName
 #24 0x5561866711e3 PyEval_EvalCode
 #25 0x55618677e1d2 run_mod
 #26 0x55618678831e PyRun_FileExFlags
 #27 0x55618678850b PyRun_SimpleFileExFlags
 #28 0x5561867895f1 pymain_main
 #29 0x55618678967c _Py_UnixMain
 #30 0x7f380cf74830 __libc_start_main
 #31 0x55618672e101 
 
Received signal 6
 #0 0x7f3759f020a5 
 #1 0x7f3758c43141 
 #2 0x7f3759f0243d 
 #3 0x7f380d32f390 
 #4 0x7f380cf89428 gsignal
 #5 0x7f380cf8b02a abort
 #6 0x7f3759f01dc5 
 #7 0x7f3759f181ed 
 #8 0x7f375955afc3 
 #9 0x7f3759559c3b 
 #10 0x7f375955a219 
 #11 0x7f375919d93a 
 #12 0x7f37591a2e76 
 #13 0x7f3758cc0600 
 #14 0x7f3758cc1b25 
 #15 0x7f3758cb0ee9 
 #16 0x7f3758cb10be QtWebEngineCore::WebContentsAdapter::WebContentsAdapter()
 #17 0x7f37caae7441 
 #18 0x7f37caae7f24 QWebEnginePage::QWebEnginePage()
 #19 0x7f37caaf5ebb QWebEngineView::page()
 #20 0x7f37e39763f9 meth_QWebEngineView_page
 #21 0x5561866a016f _PyMethodDef_RawFastCallKeywords
 #22 0x5561866d64b0 call_function
 #23 0x55618671def2 _PyEval_EvalFrameDefault
 #24 0x5561866703bd _PyEval_EvalCodeWithName
 #25 0x556186671502 _PyObject_FastCallDict
 #26 0x5561866dd16f slot_tp_init
 #27 0x5561866d5eec _PyObject_FastCallKeywords
 #28 0x55618671dea5 _PyEval_EvalFrameDefault
 #29 0x55618666fdb2 _PyEval_EvalCodeWithName
 #30 0x5561866711e3 PyEval_EvalCode
 #31 0x55618677e1d2 run_mod
 #32 0x55618678831e PyRun_FileExFlags
 #33 0x55618678850b PyRun_SimpleFileExFlags
 #34 0x5561867895f1 pymain_main
 #35 0x55618678967c _Py_UnixMain
 #36 0x7f380cf74830 __libc_start_main
 #37 0x55618672e101 
 r8: 00007f380d31a770  r9: 00007f380d743700 r10: 0000000000000008 r11: 0000000000000206
 r12: 00007ffcb48ce7e0 r13: 00000000000000ac r14: 00007ffcb48cea10 r15: 00007ffcb48cf180
 di: 00000000000073eb  si: 00000000000073eb  bp: 00007f38094c7aa0  bx: 00007ffcb48cef60
 dx: 0000000000000006  ax: 0000000000000000  cx: 00007f380cf89428  sp: 00007ffcb48ce678
 ip: 00007f380cf89428 efl: 0000000000000206 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
 [end of stack trace]
 Calling _exit(1). Core file will not be generated.

**Comment by Asphelzhn** [comment]
> 数据库不是核心功能，你直接把数据库相关代码注释了，或者随便建一个能连上的数据库就行
> […](#)
> ---原始邮件--- 发件人: "HarlingZhao"<notifications@github.com&gt; 发送时间: 2020年10月14日(周三) 晚上8:00 收件人: "DragonistYJ/EduWatching"<EduWatching@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [DragonistYJ/EduWatching] 无法连接数据库，运行出错 (#5) 运行无法连接上数据库，能否提供一下本地数据库sql，运行出错，能帮忙看一下问题吗，谢谢 (paddle) EduWatching-master$ python Main.py can't connect to db W1014 19:54:15.955312 29675 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.0 W1014 19:54:15.958451 29675 device_context.cc:243] device: 0, cuDNN Version: 7.5. Could not find QtWebEngineProcess [29675:29675:1014/195418.707230:FATAL:zygote_host_impl_linux.cc(182)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &amp;boot_pid). #0 0x7f3759f020a5 #1 0x7f3759f17eca #2 0x7f375955afc3 #3 0x7f3759559c3b #4 0x7f375955a219 #5 0x7f375919d93a #6 0x7f37591a2e76 #7 0x7f3758cc0600 #8 0x7f3758cc1b25 #9 0x7f3758cb0ee9 #10 0x7f3758cb10be QtWebEngineCore::WebContentsAdapter::WebContentsAdapter() #11 0x7f37caae7441 #12 0x7f37caae7f24 QWebEnginePage::QWebEnginePage() #13 0x7f37caaf5ebb QWebEngineView::page() #14 0x7f37e39763f9 meth_QWebEngineView_page #15 0x5561866a016f _PyMethodDef_RawFastCallKeywords #16 0x5561866d64b0 call_function #17 0x55618671def2 _PyEval_EvalFrameDefault #18 0x5561866703bd _PyEval_EvalCodeWithName #19 0x556186671502 _PyObject_FastCallDict #20 0x5561866dd16f slot_tp_init #21 0x5561866d5eec _PyObject_FastCallKeywords #22 0x55618671dea5 _PyEval_EvalFrameDefault #23 0x55618666fdb2 _PyEval_EvalCodeWithName #24 0x5561866711e3 PyEval_EvalCode #25 0x55618677e1d2 run_mod #26 0x55618678831e PyRun_FileExFlags #27 0x55618678850b PyRun_SimpleFileExFlags #28 0x5561867895f1 pymain_main #29 0x55618678967c _Py_UnixMain #30 0x7f380cf74830 __libc_start_main #31 0x55618672e101 Received signal 6 #0 0x7f3759f020a5 #1 0x7f3758c43141 #2 0x7f3759f0243d #3 0x7f380d32f390 #4 0x7f380cf89428 gsignal #5 0x7f380cf8b02a abort #6 0x7f3759f01dc5 #7 0x7f3759f181ed #8 0x7f375955afc3 #9 0x7f3759559c3b #10 0x7f375955a219 #11 0x7f375919d93a #12 0x7f37591a2e76 #13 0x7f3758cc0600 #14 0x7f3758cc1b25 #15 0x7f3758cb0ee9 #16 0x7f3758cb10be QtWebEngineCore::WebContentsAdapter::WebContentsAdapter() #17 0x7f37caae7441 #18 0x7f37caae7f24 QWebEnginePage::QWebEnginePage() #19 0x7f37caaf5ebb QWebEngineView::page() #20 0x7f37e39763f9 meth_QWebEngineView_page #21 0x5561866a016f _PyMethodDef_RawFastCallKeywords #22 0x5561866d64b0 call_function #23 0x55618671def2 _PyEval_EvalFrameDefault #24 0x5561866703bd _PyEval_EvalCodeWithName #25 0x556186671502 _PyObject_FastCallDict #26 0x5561866dd16f slot_tp_init #27 0x5561866d5eec _PyObject_FastCallKeywords #28 0x55618671dea5 _PyEval_EvalFrameDefault #29 0x55618666fdb2 _PyEval_EvalCodeWithName #30 0x5561866711e3 PyEval_EvalCode #31 0x55618677e1d2 run_mod #32 0x55618678831e PyRun_FileExFlags #33 0x55618678850b PyRun_SimpleFileExFlags #34 0x5561867895f1 pymain_main #35 0x55618678967c _Py_UnixMain #36 0x7f380cf74830 __libc_start_main #37 0x55618672e101 r8: 00007f380d31a770 r9: 00007f380d743700 r10: 0000000000000008 r11: 0000000000000206 r12: 00007ffcb48ce7e0 r13: 00000000000000ac r14: 00007ffcb48cea10 r15: 00007ffcb48cf180 di: 00000000000073eb si: 00000000000073eb bp: 00007f38094c7aa0 bx: 00007ffcb48cef60 dx: 0000000000000006 ax: 0000000000000000 cx: 00007f380cf89428 sp: 00007ffcb48ce678 ip: 00007f380cf89428 efl: 0000000000000206 cgf: 002b000000000033 erf: 0000000000000000 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000 [end of stack trace] Calling _exit(1). Core file will not be generated. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，非常感谢。在win10的机器上跑了一下，发现课程列表显示不出来，实时监控也显示不出来，我把CUDAPlace（0）换成CPUPlace()了，应该没问题吧？现在报错是js的问题，一开始是需要在Bootstrap 前引入jquery，现在是需要引入Popper，但是引入了还是报错。麻烦帮忙看一下，感激
can't connect to db
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
js: Uncaught Error: Bootstrap dropdown require Popper.js (https://popper.js.org)
js: Uncaught Error: Bootstrap dropdown require Popper.js (https://popper.js.org)
如下图，找不到实时监控的界面，内容显示也有问题。
![image](https://user-images.githubusercontent.com/11926591/96017170-3dc53500-0e7c-11eb-9407-121fd19c6b4c.png)

**Comment by Asphelzhn** [comment]
重新引入jquery和popper.js以后没有报错了，但是找不到实时监控，麻烦指点一下。如果方便的话能否留个QQ或微信，想请教一下，感激不尽

**Comment by Asphelzhn** [comment]
修改数据库文件后解决了，感谢作者的优秀工作，学习了

**Comment by shenyan887766** [comment]
> 修改数据库文件后解决了，感谢作者的优秀工作，学习了

 可否告知一下如何修改的？

**Comment by Mingjiexiaojiu** [comment]
> 修改数据库文件后解决了，感谢作者的优秀工作，学习了

老铁，数据库是咋修改的，他分享的来项目中不是没有sql文件吗
